name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: Build, Test, Fmt, Clippy
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        rust: [stable]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy
      - name: Install Ubuntu dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libasound2-dev
      - name: Build Release
        run: cargo build --release
      - name: Test
        run: cargo test --all-features
      - name: Fmt
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy -- -D warnings
